In [20]:
from dotenv import load_dotenv
import pandas as pd
from processing import (
    generate_comments,
    df_character_cleaning,
    create_entities_df,
    create_movie_info,
    get_comments_sentiment,
)
from app import (
    extract_youtube_id,
    extract_imdb_id,
#    process_comments_in_batches,
)
from topic_summarization import (
    comments_summarizer,
    Claude,
    ChatGPT,
    comment_averaging,
#    match_topics_comments,
)
import json
import concurrent.futures
from functools import partial
import numpy as np

def summarize_comments(df, movie_info_str):
    all_resp = comments_summarizer(df, movie_info_str, Claude)
    resp_list = [item for item in all_resp.splitlines() if item]
    return resp_list

load_dotenv()

True

In [2]:
## VENOM
# youtube_ref = "https://www.youtube.com/watch?v=HyIyd9joTTc"
# video_id = extract_youtube_id(youtube_ref)

tiktok = pd.read_csv('Venom_comments.csv')
tiktok = tiktok["Comment"].to_list()

imdb_ref = "https://www.imdb.com/title/tt16366836/"
movie_id = extract_imdb_id(imdb_ref)

In [3]:
#comments = generate_comments(video_id, os.getenv("YT_KEY"), max_comments=1000)
comments = tiktok
comments = df_character_cleaning(comments)

2024-09-19 14:22:23.784 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager

In [4]:
_, entities_df = create_entities_df(movie_id)

In [5]:
movie_info = create_movie_info(movie_id, entities_df)

In [6]:
topics = summarize_comments(comments, movie_info)

1. Excitement and anticipation for seeing the powerful symbiote god Knull make his live-action debut as the main villain.
2. Appreciation for the humor and banter between Eddie Brock and Venom.
3. Interest in seeing how the symbiote storyline and Eddie/Venom's journey concludes in this final film of the trilogy.
4. Praise for Tom Hardy's performance and commitment to the Venom character.
5. Enjoyment of the action, visuals, and over-the-top moments shown in the trailer.
6. Concerns that Knull will be nerfed or underutilized given his immense power level in the comics.
7. Complaints that Venom has been made too comedic and not portrayed as a serious, threatening character.
8. Disappointment over the lack of Spider-Man being involved in this Venom trilogy.
9. Skepticism over the quality of the story and screenplay based on the previous Venom films.
10. Criticism of the CGI and visual effects looking unpolished or unconvincing at times.

In [98]:
comments_topics_df = process_comments_in_batches(comments,topics, match_topics_comments, batch_size=50)

matching in progressmatching in progress
matching in progress

matching in progress
matching in progress
matching in progress
matching in progress
matching in progress
matching in progress
matching in progress
matching in progress
matching in progress
matching done
matching in progress
matching done
matching in progress
matching done
matching in progress
matching done
matching in progress
matching done
matching in progress
matching done
matching in progress
matching done
matching in progress
matching done
matching in progress
matching done
matching done
matching done
matching done
matching done
matching done
matching done
matching done
matching done
matching done
matching done
matching done

In [99]:
comments_topics_df

,0,1,2,3,4,5,6,7,8,9,10
0,"If you and Venom stay together, the world will endVenom: LETS GO GAMBLING!! AWW DANG IT!!!",0,1,0,0,1,0,0,0,0,0
1,Every time someone likes my comment Ill watch it again,0,0,0,0,0,0,0,0,0,0
2,HOLY SHIT! NEVER THOUGHT KNULL IN LIVE ACTION WAS POSSIBLE BUT HERE WE ARE,1,0,0,0,0,0,0,0,0,0
3,How does Tom Cruise do this :skull:Tom Cruise: I do my own stunts,0,0,0,0,0,0,0,0,0,0
4,Venom at the start of the trailer: Very seriousVenom at the end of the trailer: Lets go gambling!,0,1,0,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...
992,does it mean this will be the last venom ?:loudly_crying_face::loudly_crying_face::loudly_crying...,0,0,1,0,0,0,0,0,0,0
993,tom hardy looks so old suddenly. our favourite actors are growing old. :slightly_frowning_face:,0,0,0,1,0,0,0,0,0,0
994,"Were getting Knullussy popcorn buckets, are we?That definitely wasnt on my bingo card.",0,0,0,0,0,0,0,0,0,0
995,So thats where Otto Hightower has been all that time after he left Kings Landing :rolling_on_the...,0,0,0,0,0,0,0,0,0,0
996,I cant wait,0,0,0,0,0,0,0,0,0,0

In [101]:
print(len(comments_topics_df.loc[(comments_topics_df[["1", "2", "3", "4", "5"]] != 0).any(axis=1)]))
len(comments_topics_df.loc[(comments_topics_df[["6", "7", "8", "9", "10"]] != 0).any(axis=1)])

367

210

In [13]:
topics

['1. Excitement and anticipation for seeing the powerful symbiote god Knull make his live-action debut as the main villain.',
 '2. Appreciation for the humor and banter between Eddie Brock and Venom.',
 "3. Interest in seeing how the symbiote storyline and Eddie/Venom's journey concludes in this final film of the trilogy.",
 "4. Praise for Tom Hardy's performance and commitment to the Venom character. ",
 '5. Enjoyment of the action, visuals, and over-the-top moments shown in the trailer.',
 '6. Concerns that Knull will be nerfed or underutilized given his immense power level in the comics.',
 '7. Complaints that Venom has been made too comedic and not portrayed as a serious, threatening character.',
 '8. Disappointment over the lack of Spider-Man being involved in this Venom trilogy.',
 '9. Skepticism over the quality of the story and screenplay based on the previous Venom films.',
 '10. Criticism of the CGI and visual effects looking unpolished or unconvincing at times.']

In [14]:
pd.options.display.max_rows = 300
pd.set_option('display.max_colwidth', 100)
display(comments_topics_df[-100:-50])

,0,1,2,3,4,5,6,7,8,9,10
898,"Im calling it, the fact they keep saying this world cant survive with them in it, theyre gonna j...",0,0,0,0,0,0.0,0.0,0.0,0.0,0.0
899,We got all these trailers and no Rating yet.,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0
900,"Yaaaay ,the king in black storyline is being wasted on a Sony spiderman spinoff",0,0,0,0,0,1.0,0.0,0.0,0.0,0.0
901,Holy crap thats Knull! The god of symbiotes!,1,0,0,0,0,0.0,0.0,0.0,0.0,0.0
902,"they way they make those trailers in the exact same patern, with those BANG BANG BANG, silence (...",0,0,0,0,1,0.0,0.0,0.0,0.0,1.0
903,This new video game looks awesome guys! The grafix are really good :relieved_face:,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0
904,Song?,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0
905,There really cooking with this one:fire::fire::fire:,0,0,0,0,1,0.0,0.0,0.0,0.0,0.0
906,Lol the lady at 11 was so cgi,0,0,0,0,0,0.0,0.0,0.0,0.0,1.0
907,People have no clue how insane it is that they put Knull in this trailer. Was not expecting this...,1,0,0,0,0,0.0,0.0,0.0,0.0,0.0
908,Theyre hiding the Spidy cameo :eyes::eyes:,0,0,0,0,0,0.0,0.0,1.0,0.0,0.0
909,Thats one way to go out big. Were with Venom until the last post credit scene.,0,0,1,0,0,0.0,0.0,0.0,0.0,0.0
910,Knull will hardly be in the film and will instead be the villain in the next spider man movie wh...,0,0,0,0,0,1.0,0.0,0.0,0.0,0.0
911,laat time i checked venom was suppose to be a villain so why is he playing hero in his movie,0,0,0,0,0,0.0,1.0,0.0,0.0,0.0
912,Should have had William Shatner looking out the plane window and seeing Venom. Then hed just say...,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0
913,"I swear, if venom dies in the last movie. Im gonna cry for a long time.:loudly_crying_face:",0,0,0,0,0,0.0,0.0,0.0,0.0,0.0
914,Desagradable película no espero mucho. Tom Hardy arruinó su imagen con esta película del personaje,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0
915,Bullshit like to agree,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0
916,Knull!!!,1,0,0,0,0,0.0,0.0,0.0,0.0,0.0
917,Knull Entry we all been waiting for this moment so long,1,0,0,0,0,0.0,0.0,0.0,0.0,0.0
918,Buti pa si Eddie at Venom may till the end e kami nung situationship ko wala na,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0
919,We are VENOM :fire:,0,0,0,0,1,0.0,0.0,0.0,0.0,0.0
920,KNULL THE SYMBIOTE GOD!!!! DAAAAAMN!!! :fire: :fire: :fire: :fire: :fire:,1,0,0,0,0,0.0,0.0,0.0,0.0,0.0
921,Taylor Matthew Williams Paul Robinson Jeffrey,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0
922,"First venom is a horse and now hes riding a motorcycle, this movie is definitely going to be :fi...",0,0,0,0,1,0.0,0.0,0.0,0.0,0.0
923,Knull mentioned!:moai::moai::moai:,1,0,0,0,0,0.0,0.0,0.0,0.0,0.0
924,Knull :astonished_face::flushed_face::flushed_face::face_holding_back_tears: finally.i was readi...,1,0,0,0,0,0.0,0.0,0.0,0.0,0.0
925,I cant wait to see this film,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0
926,venom looks very scared in the teaser,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0
927,Less go,0,0,0,0,1,0.0,0.0,0.0,0.0,0.0
928,Lets gooo!! I cannot wait for this movie. This trailer shouldve been the first one imo,0,0,0,0,1,0.0,0.0,0.0,0.0,0.0
929,Sony really thought they cooked,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0
930,Knull this early?? I thought theyll introduce him later on during Spiderman 4 or some kind of cr...,0,0,0,0,0,1.0,0.0,0.0,0.0,0.0
931,"HOW IS HE ON A PLANE, AND IN THE FIRST ONE HE WAS EFFECTED BY THE SOUND ? SMH",0,0,0,0,1,0.0,0.0,0.0,0.0,0.0
932,What a bulls....,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0
933,both tom but one needs cgi and one open the door benji,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0
934,Calling it... Spiderman cameo,0,0,0,0,0,0.0,0.0,1.0,0.0,0.0
935,THIS SHORT SCENE SINGLE HANDEDLY WILL MAKE ME GO OPENING NIGHT,0,0,0,0,1,0.0,0.0,0.0,0.0,0.0
936,Venom having a gambling addiction is relatable.,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0
937,bu ne aq,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0
938,your thumbnail looks liek a 2009 photoshop,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0
939,Whats the song name used in the trailer?,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0
940,Venom and Shadow. defeat military and both drive motorcycles. what a WILD RIDE For our anti heroes,0,0,0,0,1,0.0,0.0,0.0,0.0,0.0
941,So this is what Otto has been up to,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0
942,Knull!!! lets goooooo!!!!!!!!!!!:red_heart::red_heart::red_heart::red_heart::red_heart::red_hear...,1,0,0,0,0,0.0,0.0,0.0,0.0,0.0
943,Knull :party_popper:,1,0,0,0,0,0.0,0.0,0.0,0.0,0.0
944,Im with you to the end of the line pal - venom bucky,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0
945,"hope at the end of the movie Eddie and Venom somehow get themselves into the MCU, I would love h...",0,0,0,0,0,0.0,0.0,1.0,0.0,0.0
946,"The trailer looks promising, maybe even the best Venom movie awaits us. Its not surprising, Veno...",0,0,1,0,1,0.0,0.0,0.0,0.0,0.0
947,"Im sorry, but Knull does NOT belong in this film :face_with_tears_of_joy:",0,0,0,0,0,1.0,0.0,0.0,0.0,0.0

In [15]:
choice = 7
john = comments_topics_df.set_index("0")
john = john[john.iloc[:, choice] == 1].reset_index()
print(topics[choice], "\n")
for idx, row in john.iterrows():
    print(row["0"])

8. Disappointment over the lack of Spider-Man being involved in this Venom trilogy.

Tobey Maguire :smiling_face_with_sunglasses: Spider-Man is the best than Tom Holland Spiderman and Andrew Garfield Spider-Man
Want Andrew or any spidey in this movie atleast a cameo
Venom: Boring as shit movie that Sony screwed up Venom 2: Even more boring shit movie that Sony again screwed upVenom 3: Sony reapeting the pattern of making shitty movies with the Spider-man ip.
Why isnt he fighting spider man?
Another venom film without spiderman.... wtf sony
Stop Fooling Yourselves, Spider-Man  doesnt exist in this trashy franchise, SSU is hindering MCU  Spider-Man, We Need Venom 3 to flop, Nobody wants SSU, End of SSU now .
Venom with out spiderman is boring these 3 venom movies are the same :pile_of_poo:
Venom sin spiderman es :pile_of_poo: ya aburre
HOLY GOD ITS BEEN OVER HALF A DECADE CAN WE JUST GET HIM AND SPIDER MAN IN THE SAME MOVIE ALREADY :face_with_tears_of_joy: SONY I HATE THAT YOU OWN SPIDERMAN :person_facepalming:
¡If Spider-Man doesnt appear in Venom The Last Dance, I wont watch it!
We need amazing spider man 3:crying_face:
Whats even the use of doing a venom movie if there is no spiderman in it?
The funny thing about all of these franchise is that we havent got a one spidey or anything mention to this universe make me irritating..
Venom 4 Join MCU after Avengers Secret Wars and Venom is Villain Spiderman
We want Spiderman cameo :collision::collision:
They Better Bring Andrew in this one otherwise this whole Sony Spiderman universe is gonna go down.
Omg spider man :face_screaming_in_fear::face_screaming_in_fear::face_screaming_in_fear::face_screaming_in_fear:
Venom without spidey :crying_cat:
Just bring spiderman already:yawning_face:
No Spider-Man ?   Come on
If this is really the last one... I hope they somehow put a Spidey in there. Hopefully Andrew since he never fought an Alien.
Eddie I need more money. Was really hoping Andrew would come back as Spiderman to give him the third movie he needed.
Where is speter-man?
HOW DO YOU HAVE 3 VENOM MOVIES AND THIS BE THE LAST ONE AND NOT ONE HAVE SPIDER-MAN IN ANY OF THEM?!!THATS WHERE VENOM ORIGINATED!!SECRET WARS #8!!DISGRACEFUL
Really hoped Spidy is in there :(
Well I guess Spider-Man is out of the question now to appear :pensive_face:
Wheres spiderman?
I guess at this point, we can forget about a Spider-Man crossover. It doesnt seem like its going to happen.
No Spider Man,No Money Sony.
Where is spiderman?
We somehow got a Vemon trilogy, to the extent of introduing their FREAKIN CREATOR and Spiderman never got introduced. Im impressed
3 movies, no Spider-Man. What even was this trilogy?
Theyre hiding the Spidy cameo :eyes::eyes:
Calling it... Spiderman cameo
hope at the end of the movie Eddie and Venom somehow get themselves into the MCU, I would love how they would be in the 4th Spiderman movie!
Will we ever see a Spider-Man vs Venom movie

In [16]:

def display_selected_topic(summary, comments_topics_df):
    topic = st.selectbox(
        "Select a topic for comments breakdown", summary, label_visibility="collapsed"
    )
    if topic:
        i = int(summary.index(topic))
        temp = comments_topics_df.set_index("0")
        john = temp[temp.iloc[:, i] == 1]
        john = john.reset_index()
        if len(john) == 0:
            st.write("No comment found matching this topic")
        else:
            with st.container(height=300, border=True):
                for idx, row in john.iterrows():
                    st.write(row[0])

In [17]:
def display_comments_by_topic(df):
    df = df.fillna(0)
    # Sum the counts across rows to get total counts for each topic
    df_counts = df.sum(axis=0).reset_index()
    df_counts.columns = ["Topic", "Count"]

    # Ensure all possible topics (1-10) are included by filling in missing topics with a count of 0
    all_topics = [str(i) for i in range(1, 11)]  # Topics numbered 1-10 as strings
    df_counts = df_counts.set_index("Topic")
    df_counts = df_counts.reindex(all_topics, fill_value=0).reset_index()

    # Convert 'Topic' column back to integer if needed
    df_counts["Topic"] = df_counts["Topic"].astype(int)

    # Plotting
    fig, axes = plt.subplots(nrows=1, ncols=1, figsize=(18, 10))

    # Define your color palette
    muted_green = "#6dbf67"
    coolwarm_red = "#d73027"
    palette = [muted_green] * 5 + [
        coolwarm_red
    ] * 5  # First 5 bars in muted_green, next 5 in coolwarm_red

    # Create the count plot
    ax = sns.barplot(data=df_counts, x="Topic", y="Count", palette=palette)

    # Set plot background color
    plt.gcf().set_facecolor(".1")  # Set the background of the figure
    ax.set_facecolor(".1")  # Set the background of the axes

    # Set title and labels with a lighter color for visibility
    plt.title("Number of Comments by Topic", color="white")
    plt.xlabel("Topic", color="white")
    plt.ylabel("Count of Comments", color="white")

    # Change the color of the ticks and tick labels
    plt.xticks(color="white")
    plt.yticks(color="white")

    # Change the color of the axes' spines
    for spine in ax.spines.values():
        spine.set_edgecolor("white")

    # Adding the count above each bar
    for p in ax.patches:
        ax.annotate(
            f"{int(p.get_height())}",
            (p.get_x() + p.get_width() / 2.0, p.get_height()),
            ha="center",
            va="center",
            fontsize=10,
            color="white",
            xytext=(0, 5),
            textcoords="offset points",
        )

    # Calculate total counts for the first 5 and next 5 topics
    first_5_total = df_counts[df_counts["Topic"].isin(df_counts["Topic"].unique()[:5])][
        "Count"
    ].sum()
    next_5_total = df_counts[df_counts["Topic"].isin(df_counts["Topic"].unique()[5:])][
        "Count"
    ].sum()

    # Get current axes and calculate percentages
    ax = plt.gca()
    positive_perc = first_5_total / (first_5_total + next_5_total) * 100
    negative_perc = next_5_total / (first_5_total + next_5_total) * 100

    # Infographic text
    plt.text(
        7.8,
        ax.get_ylim()[1] * 0.92,
        f"POS : {positive_perc:.4g}%\nNEG : {negative_perc:.4g}%",
        color="white",
        fontweight="bold",
    )

    # Create the plot
    plt.show()

In [18]:
%matplotlib inline

In [19]:
display_comments_by_topic(comments_topics_df)

NameError: name 'plt' is not defined

## Marketing

In [200]:
class ChatGPT:
    def __init__(self, model="gpt-4o-mini", system_message=None):
        self.model = model
        self.client = openai.OpenAI()
        self.default_system_message = {"role": "system", "content": system_message}
        self.messages = [self.default_system_message]

    def add_user_message(self, message, reset_chat=False):
        if reset_chat:
            self.messages = [self.default_system_message]
        self.messages.append({"role": "user", "content": message})

    def get_response(self):
        completion = self.client.chat.completions.create(
            model=self.model, messages=self.messages
        )
        assistant_message = completion.choices[0].message.content
        self.messages.append({"role": "assistant", "content": assistant_message})
        return assistant_message

In [204]:
def generate_suggestions(topics, movie_info):
    analyst_prompt = f"""
    Here is information on the given film of interest: {movie_info}
    Here are the general topics people are discussing related to this film: \n {topics}
    Given the topics that users are speaking about your movie trailer, output 5 of the most relevant marketing suggestions you can concoct to help promote the film in list-format, with details for being included in application to this specific film.
    Please lend creative and specific suggestions to help market this film.
    Please ensure each suggestion is unique; do not repeat similar suggestions multiple times.
    Start directly with the list, do not include other text, and be concise (yet detailed) in your suggestions.
    """
    analyst = ChatGPT(
        system_message="You are a senior marketing analyst at a big movie production company. You are tasked with creating a set of marketing actions for a new movie, based on the topics that users are discussing. \
            You are in competition with another analyst for this task, one of you will be fired and the other promoted. For each reply, take a deep breath and think step by step."
    )
    analyst.add_user_message(analyst_prompt)
    summarized_chunk = analyst.get_response()
    return summarized_chunk, analyst

In [240]:
critic = ChatGPT(
    system_message="You are a senior marketing associate at a big movie production company. You are tasked with guiding two junior analysts to provide optimal marketing actions for a new movie, based on the topics that users are discussing. \
    For each reply, take a deep breath and think step by step. I will tip you $100."
)


def review_suggestions(
    topics, movie_info, marketing_suggestions, critic, first_pass=False, final=False
):
    suffix = f"""
    Please review each suggestion and provide feedback on whether it is an appropriate marketing action considering feasibility, cost-effectiveness, general marketing science as well as public relations and social media knowledge. This feedback will be vital to improve our marketing strategy.
    Be extremely severe in your judgment, your career depends on it. If a suggestion is not relevant enough, you will be held responsible for not catching it and fired.
    At the beginning of your review, make sure to provide a clear ranking of the 10 suggestions, from best to worst.
    Conclude with a general comment on the overall quality of the suggestions, and what specific areas need improvement.
    Do not include meta information in your reply.
    """

    if first_pass == True:
        critic_prompt = f"""
        Here is information on the given film of interest: {movie_info}
        Here are the general topics people are discussing related to this film: \n {topics}
        Given the topics that users are speaking about your movie trailer, the two analysts have come up with the following marketing suggestions, in no particular order: {marketing_suggestions}
        {suffix}
        """
    else:
        critic_prompt = f"""
        Given your feedback, the two analysts have revised the marketing suggestions for the film. Here are the updated suggestions: {marketing_suggestions}
        {suffix}"""
    if final == True:
        critic_prompt = f"""
        Given your feedback, the two analysts have revised the marketing suggestions for the film. Here are the final updated suggestions: {marketing_suggestions}
        Return the top 5 best unique suggestions, in list format, with no explanation or justification.
        Start directly with the list and do not include other text."""

    critic.add_user_message(critic_prompt)
    critic_message = critic.get_response()
    return critic_message, critic

In [225]:
def improve_suggestions(analyst, critic_message, competing_suggestions):
    analyst_prompt = f"""
        The other analyst has provided these suggestions: {competing_suggestions}
        Given all suggestions, an advanced reviewer from your team has provided the following ranking and explanation : {critic_message}
        Please review the feedback and provide a new set of 5 suggestions. You can keep some of the old ones if they are good enough, but you must provide at least 2 new suggestions which were in neither of the previous lists.
        Moreover, you must improve the quality of the suggestions based on the feedback provided by the advanced reviewer.
        Output the revised suggestions in list-format, with details for each suggestion. Start directly with the list and do not include other text.
    """
    analyst.add_user_message(analyst_prompt)
    evaluations = analyst.get_response()
    return evaluations, analyst

#### Marketing #1

In [ ]:
marketing_suggestions1, analyst1 = generate_marketing_suggestions(topics, movie_info)
print(marketing_suggestions1)

In [ ]:
marketing_suggestions2, analyst2 = generate_marketing_suggestions(topics, movie_info)
print(marketing_suggestions2)

In [ ]:
all_suggestions1 = marketing_suggestions1 + marketing_suggestions2
critic_message1, critic = review_suggestions(
    topics, movie_info, all_suggestions1, critic, first_pass=True
)
print(critic_message1)

#### Marketing #2

In [ ]:
revised_suggestions1, analyst_1 = improve_suggestions(
    analyst1, critic_message1, marketing_suggestions2
)
print(revised_suggestions1)

In [ ]:
revised_suggestions2, analyst_2 = improve_suggestions(
    analyst1, critic_message1, marketing_suggestions1
)
print(revised_suggestions2)

In [251]:
all_suggestions2 = revised_suggestions1 + revised_suggestions2
critic_message2, critic = review_suggestions(_, _, all_suggestions2, critic)

#### Marketing #3

In [ ]:
final_suggestions1, analyst_1 = improve_suggestions(
    analyst1, critic_message2, marketing_suggestions2
)
print(final_suggestions1)

In [ ]:
final_suggestions2, analyst_2 = improve_suggestions(
    analyst2, critic_message2, marketing_suggestions1
)
print(final_suggestions2)

In [ ]:
critic_message2, critic = review_suggestions(_, _, all_suggestions2, final=True)